{% set name = "pre_commit" %}
{% set version = "1.18.3" %}
{% set hash_type = "sha256" %}
{% set hash = "59fa9723919fbc42fc0b14f5240142ebb4b104fcac2c2aca7c802260b93cdaeb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/pre-commit/pre-commit/archive/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: pip install . --no-deps --ignore-installed
  entry_points:
    - pre-commit = pre_commit.main:main
    - pre-commit-validate-config = pre_commit.clientlib:validate_config_main
    - pre-commit-validate-manifest = pre_commit.clientlib:validate_manifest_main

requirements:
  build:
    - pip
    - python

  run:
    - aspy.yaml
    - cached-property
    - cfgv >=2.0.0
    - futures  # [py<32]
    - identify >=1.0.0
    - importlib_metadata
    - importlib_resources  # [py<37]
    - nodeenv >=0.11.1
    - python
    - pyyaml
    - setuptools
    - six
    - toml
    - virtualenv >=15.2

test:
  imports:
    - pre_commit
    - pre_commit.commands
    - pre_commit.languages
  commands:
    - pre-commit --help
    - pre-commit-validate-config --help
    - pre-commit-validate-manifest --help

about:
  home: http://pre-commit.com/
  license: MIT
  license_file: LICENSE
  summary: 'A framework for managing and maintaining multi-language pre-commit hooks.'
  license_family: MIT
  dev_url: https://github.com/pre-commit/pre-commit
  doc_url: https://github.com/pre-commit/pre-commit

extra:
  recipe-maintainers:
    - nicoddemus
    - deadsnakes-issues-bot
    - xmnlab
